title: 某某的故纸堆
theme: default
port: 8080
sort: date
show_toc: true
top_tags: [php, python]
github:

authors:
    john:
        name: John Doe
        avatar: static/avatars/john.jpg
        intro:
    ryan:
        name: Ryan Liu
        avatar: static/avatars/ryan.jpg
        intro:

footer:
    copyright:
    from_year:
    cn_cert_no:
